services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.4.0
    restart: unless-stopped
    env_file:
      - ./.env
    command: --init-file /data/application/init.sql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./infra/database.init.sql:/data/application/init.sql
      # - ./infra/database.init.sql:/docker-entrypoint-initdb.d
  api:
    container_name: api
    build: ./
    depends_on:
      - mysqldb
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./src:/src

volumes:
  db: 
  infra: